---
- hosts: all
  become: true
  tasks:
  - name: Copy keepalived.conf
    copy:
      src: /vagrant/keepalived-master1.conf
      dest: /etc/keepalived/keepalived.conf
      owner: root
      group: root
      mode: 0644