---
- hosts: all
  become: true
  tasks:
  - name: Start Keepalived
    systemd:
      name: keepalived
      state: started
      enabled: True
  
  - name: Start etcd
    systemd:
      name: etcd
      state: started
      no_block: yes
      enabled: True

  - name: Enable kubelet
    systemd:
      name: kubelet
      enabled: True