---
- hosts: all
  become: true
  tasks:
  - name: Set PRIVATE_IP
    shell: ifconfig eth1 | grep 'inet ' | awk '{print $2}'
    register: private_ip

  - set_fact:
      api_server_ip: "{{ private_ip.stdout }}"

  - name: Copy config.yaml template
    template:
      src: /vagrant/config.yaml.j2
      dest: /vagrant/config.yaml

  - name: Run kubeadm init
    shell: kubeadm init --config=/vagrant/config.yaml