---
- hosts: all
  become: true
  tasks:
  - name: Set PRIVATE_IP
    shell: ifconfig eth1 | grep 'inet ' | awk '{print $2}'
    register: private_ip

  - set_fact:
      api_server_ip: "{{ private_ip.stdout }}"

  - name: Copy etcd.service template
    template:
      src: /vagrant/etcd.service.j2
      dest: /etc/systemd/system/etcd.service    

  - name: Run kubeadm init
    shell: kubeadm init --config=/vagrant/config.yaml
  
  - name: Start etcd
    systemd:
      name: etcd
      state: started
      enabled: True